apiVersion: kuma.io/v1alpha1
kind: FaultInjection
mesh: default
metadata:
  name: delay
spec:
  sources:
    - match:
        kuma.io/service: frontend_kuma-demo_svc_8080
        kuma.io/protocol: http
  destinations:
    - match:
        kuma.io/service: backend_kuma-demo_svc_3001
        kuma.io/protocol: http
  conf:        
    delay:
      percentage: 20
      value: 5s