apiVersion: kuma.io/v1alpha1
kind: HealthCheck
mesh: default
metadata:
  name: backend-to-db-check
spec:
  sources:
  - match:
      kuma.io/service: backend_kuma-demo_svc_3001
  destinations:
  - match:
      kuma.io/service: postgres_kuma-demo_svc_5432
  conf:
    interval: 1s
    timeout: 2s
    unhealthyThreshold: 1
    healthyThreshold: 5
    failTrafficOnPanic: true
    alwaysLogHealthCheckFailures: true 
    tcp:
      send: Zm9v
      receive:
      - YmFy
      - YmF6